name: docker-mern
on:
    push:
        branched: [ main ]

jobs: 
    docker:
        runs-on: ubuntu-latest
        steps:
            - name: checkout
              uses: actions/checkout@v2

            - name: Login Docker Hub
              uses: docker/login-action@v1
              with:
                username: ${{ secrets.DOCKERHUB_USERNAME }}
                password: ${{ secrets.DOCKERHUB_ACCESS_TOKEN }}

            - name: Setup Docker BuildX
              uses: docker/setup-buildx-actions@v1
              id: buildX

            - name: Build and Push Docker Image
              uses: docker/build-push-action@v2
              id: docker_build
              with:
                context: ./
                file: ./Dockerfile
                builder: ${{ steps.buildX.outputs.name }}
                push: true
                tags: ${{ secrets.DOCKERHUB_USERNAME }}/Docker-MERN

            - name: verify
              run: echo ${{ steps.docker_build.outputs.digest }}